<?php

namespace ExpressionEngine\Addons\Mcp\Mcp\Resources;

use ExpressionEngine\Addons\Mcp\Attributes\EeCategory;
use ExpressionEngine\Addons\Mcp\Services\FieldTemplateStructureService;
use ExpressionEngine\Addons\Mcp\Support\AbstractResource;
use Mcp\Capability\Attribute\McpResource;
use Mcp\Capability\Attribute\McpResourceTemplate;

/**
 * Field Template Structures Resource
 *
 * Exposes CLI-generated field template scaffolds via MCP resources.
 */
#[EeCategory('developer')]
class FieldTemplateStructuresResource extends AbstractResource
{
    public function uri(): string
    {
        return 'ee://field-template-structures';
    }

    public function name(): ?string
    {
        return 'field_template_structures';
    }

    public function description(): ?string
    {
        return 'Discover and fetch exact field template scaffold code generated by ExpressionEngine CLI. Use for complex fields (Grid/Fluid/Matrix/File/Relationship/RTE).';
    }

    /**
     * List recommended fields and usage guidance.
     */
    #[McpResource(
        uri: 'ee://field-template-structures',
        name: 'field_template_structures_list',
        description: 'List recommended fields and guidance for CLI-generated field template structures'
    )]
    public function listFieldTemplateStructures(): mixed
    {
        return $this->buildListData();
    }

    /**
     * Get scaffold by field short name.
     */
    #[McpResourceTemplate(
        uriTemplate: 'ee://field-template-structures/{fieldName}',
        name: 'field_template_structure',
        description: 'Get CLI-generated template scaffold for a field by field short name'
    )]
    public function getFieldTemplateStructure(string $fieldName): mixed
    {
        return $this->buildFieldDataByName($fieldName);
    }

    /**
     * Get scaffold by field ID.
     */
    #[McpResourceTemplate(
        uriTemplate: 'ee://field-template-structures/id/{fieldId}',
        name: 'field_template_structure_by_id',
        description: 'Get CLI-generated template scaffold for a field by field ID'
    )]
    public function getFieldTemplateStructureById(string $fieldId): mixed
    {
        if (! is_numeric($fieldId)) {
            throw new \InvalidArgumentException('fieldId must be numeric.');
        }

        return $this->buildFieldDataById((int) $fieldId);
    }

    public function validateParams(array $params): void
    {
        if (isset($params['field_id']) && ! is_numeric($params['field_id'])) {
            throw new \InvalidArgumentException('field_id must be a numeric value.');
        }
    }

    public function fetch(array $params = []): mixed
    {
        $fieldName = $params['field_name'] ?? $params['fieldName'] ?? null;
        $fieldId = $params['field_id'] ?? $params['fieldId'] ?? null;

        if ($fieldId !== null) {
            if (! is_numeric($fieldId)) {
                throw new \InvalidArgumentException('field_id must be a numeric value.');
            }

            return $this->buildFieldDataById((int) $fieldId);
        }

        if ($fieldName !== null && trim((string) $fieldName) !== '') {
            return $this->buildFieldDataByName((string) $fieldName);
        }

        return $this->buildListData();
    }

    /**
     * List endpoint payload.
     */
    private function buildListData(): array
    {
        $service = new FieldTemplateStructureService();
        $data = $service->listRecommendedFields();

        $data['usage'] = [
            'tool' => 'get_field_template_structure',
            'resource_template_by_name' => 'ee://field-template-structures/{fieldName}',
            'resource_template_by_id' => 'ee://field-template-structures/id/{fieldId}',
            'why' => 'Prefer generated scaffold for complex fields to avoid incorrect tag nesting and variable names.',
        ];

        return $data;
    }

    /**
     * Detail payload by field name.
     */
    private function buildFieldDataByName(string $fieldName): array
    {
        $service = new FieldTemplateStructureService();
        $result = $service->generateForFieldName(
            trim($fieldName),
            'index'
        );

        return [
            'field' => $result['field'],
            'template' => $result['template'],
            'template_code' => $result['template_code'],
            'is_complex_field' => $result['is_complex_field'],
            'recommended_for' => $result['recommended_for'],
            'when_to_use' => 'Use this resource when you need exact, field-specific template syntax generated by EE CLI.',
            'generated_at' => $result['generated_at'],
        ];
    }

    /**
     * Detail payload by field ID.
     */
    private function buildFieldDataById(int $fieldId): array
    {
        $service = new FieldTemplateStructureService();
        $result = $service->generateForFieldId(
            $fieldId,
            'index'
        );

        return [
            'field' => $result['field'],
            'template' => $result['template'],
            'template_code' => $result['template_code'],
            'is_complex_field' => $result['is_complex_field'],
            'recommended_for' => $result['recommended_for'],
            'when_to_use' => 'Use this resource when you need exact, field-specific template syntax generated by EE CLI.',
            'generated_at' => $result['generated_at'],
        ];
    }
}
