<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit83099b9fa8cd2216827ab086114aacad
{
    public static $files = array (
        'a4a119a56e50fbb293281d9a48007e0e' => __DIR__ . '/..' . '/symfony/polyfill-php80/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'B' => 
        array (
            'BoldMinded\\Ansel\\Dependency\\Symfony\\Polyfill\\Php80\\' => 51,
            'BoldMinded\\Ansel\\Dependency\\Symfony\\Component\\Process\\' => 54,
            'BoldMinded\\Ansel\\Dependency\\Symfony\\Component\\OptionsResolver\\' => 62,
            'BoldMinded\\Ansel\\Dependency\\Psr\\Log\\' => 36,
            'BoldMinded\\Ansel\\Dependency\\Litzinger\\Basee\\' => 44,
            'BoldMinded\\Ansel\\Dependency\\ImageOptimizer\\' => 43,
            'BoldMinded\\Ansel\\Dependency\\Bamarni\\Composer\\Bin\\' => 49,
            'BoldMinded\\Ansel\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'BoldMinded\\Ansel\\Dependency\\Symfony\\Polyfill\\Php80\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php80',
        ),
        'BoldMinded\\Ansel\\Dependency\\Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'BoldMinded\\Ansel\\Dependency\\Symfony\\Component\\OptionsResolver\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/options-resolver',
        ),
        'BoldMinded\\Ansel\\Dependency\\Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'BoldMinded\\Ansel\\Dependency\\Litzinger\\Basee\\' => 
        array (
            0 => __DIR__ . '/..' . '/litzinger/basee/src',
        ),
        'BoldMinded\\Ansel\\Dependency\\ImageOptimizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/ps/image-optimizer/src/ImageOptimizer',
        ),
        'BoldMinded\\Ansel\\Dependency\\Bamarni\\Composer\\Bin\\' => 
        array (
            0 => __DIR__ . '/..' . '/bamarni/composer-bin-plugin/src',
        ),
        'BoldMinded\\Ansel\\' => 
        array (
            0 => __DIR__ . '/../../../..' . '/addons/ansel',
        ),
    );

    public static $classMap = array (
        'BoldMinded\\Ansel\\Dependency\\Attribute' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Attribute.php',
        'BoldMinded\\Ansel\\Dependency\\PhpToken' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/PhpToken.php',
        'BoldMinded\\Ansel\\Dependency\\Stringable' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/Stringable.php',
        'BoldMinded\\Ansel\\Dependency\\UnhandledMatchError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/UnhandledMatchError.php',
        'BoldMinded\\Ansel\\Dependency\\ValueError' => __DIR__ . '/..' . '/symfony/polyfill-php80/Resources/stubs/ValueError.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit83099b9fa8cd2216827ab086114aacad::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit83099b9fa8cd2216827ab086114aacad::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit83099b9fa8cd2216827ab086114aacad::$classMap;

        }, null, ClassLoader::class);
    }
}
