<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'BoldMinded\\Ansel\\Dependency\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'BoldMinded\\Ansel\\Dependency\\Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'BoldMinded\\Ansel\\Dependency\\Symfony\\Component\\OptionsResolver\\' => array($vendorDir . '/symfony/options-resolver'),
    'BoldMinded\\Ansel\\Dependency\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'BoldMinded\\Ansel\\Dependency\\Litzinger\\Basee\\' => array($vendorDir . '/litzinger/basee/src'),
    'BoldMinded\\Ansel\\Dependency\\ImageOptimizer\\' => array($vendorDir . '/ps/image-optimizer/src/ImageOptimizer'),
    'BoldMinded\\Ansel\\Dependency\\Bamarni\\Composer\\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'),
    'BoldMinded\\Ansel\\' => array($baseDir . '/addons/ansel'),
);
