<?php

namespace ExpressionEngine\Addons\Mcp\Services;

if (! defined('BASEPATH')) {
    exit('No direct script access allowed');
}

/**
 * Template Tag Syntax Service
 *
 * Provides lightweight analysis and repair helpers for ExpressionEngine field
 * template snippets, focused on complex field tag-pair syntax.
 */
class TemplateTagSyntaxService
{
    /**
     * Field types where tag-pair syntax is typically required.
     */
    public const COMPLEX_FIELD_TYPES = [
        'grid',
        'fluid_field',
        'matrix',
        'relationship',
        'file',
        'file_grid',
        'rte',
    ];

    public function isComplexFieldType(string $fieldType): bool
    {
        return in_array($fieldType, self::COMPLEX_FIELD_TYPES, true);
    }

    /**
     * Analyze snippet validity for the provided field syntax expectations.
     *
     * @return array{
     *   valid: bool,
     *   errors: array<int, string>,
     *   warnings: array<int, string>,
     *   suggestions: array<int, string>,
     *   metrics: array<string, int|bool>
     * }
     */
    public function analyzeSnippet(string $snippet, ?string $fieldName = null, bool $expectTagPair = false): array
    {
        $errors = [];
        $warnings = [];
        $suggestions = [];

        $trimmed = trim($snippet);
        if ($trimmed === '') {
            $errors[] = 'Template snippet is empty.';
            $suggestions[] = 'Provide at least one field tag.';
        }

        $openBraceCount = substr_count($snippet, '{');
        $closeBraceCount = substr_count($snippet, '}');
        if ($openBraceCount !== $closeBraceCount) {
            $warnings[] = 'Curly-brace counts are unbalanced, which usually indicates malformed template tags.';
        }

        $hasFieldOpen = false;
        $hasFieldClose = false;
        $hasFieldSingle = false;

        if ($fieldName !== null && $fieldName !== '') {
            $hasFieldOpen = $this->hasOpeningTag($snippet, $fieldName);
            $hasFieldClose = $this->hasClosingTag($snippet, $fieldName);
            $hasFieldSingle = $this->hasSingleTag($snippet, $fieldName);

            if (! $hasFieldOpen && ! $hasFieldClose) {
                $errors[] = "Snippet does not reference field '{$fieldName}'.";
                $suggestions[] = "Add the field tag `{{$fieldName}}`.";
            }

            if ($hasFieldClose && ! $hasFieldOpen) {
                $errors[] = "Found closing tag `{/{$fieldName}}` without opening tag.";
                $suggestions[] = "Add opening tag `{{$fieldName}}` before the closing tag.";
            }

            if ($expectTagPair) {
                if ($hasFieldOpen && ! $hasFieldClose) {
                    $errors[] = "Missing closing tag `{/{$fieldName}}`.";
                    $suggestions[] = "Add closing tag `{/{$fieldName}}`.";
                }

                if ($hasFieldSingle && ! $hasFieldClose) {
                    $warnings[] = "Complex field '{$fieldName}' is usually rendered as a tag pair, not a single tag.";
                    $suggestions[] = 'Use generated scaffold from get_field_template_structure.';
                }
            }
        }

        return [
            'valid' => empty($errors),
            'errors' => array_values(array_unique($errors)),
            'warnings' => array_values(array_unique($warnings)),
            'suggestions' => array_values(array_unique($suggestions)),
            'metrics' => [
                'open_braces' => $openBraceCount,
                'close_braces' => $closeBraceCount,
                'has_field_open' => $hasFieldOpen,
                'has_field_close' => $hasFieldClose,
                'has_field_single' => $hasFieldSingle,
            ],
        ];
    }

    /**
     * Explain expected syntax patterns and common mistakes for field type.
     *
     * @return array{
     *   syntax_style: string,
     *   key_rules: array<int, string>,
     *   common_mistakes: array<int, string>
     * }
     */
    public function explainFieldSyntax(string $fieldName, string $fieldType): array
    {
        $complex = $this->isComplexFieldType($fieldType);

        $keyRules = [
            "Use the exact field short name in tags: `{{$fieldName}}`.",
            'Prefer scaffold generated by `get_field_template_structure` for production templates.',
        ];

        $commonMistakes = [
            'Using the field label instead of the short name.',
            'Mismatched or missing curly braces in template tags.',
        ];

        if ($complex) {
            $keyRules[] = "Render as tag pair: `{{$fieldName}} ... {/{$fieldName}}`.";
            $keyRules[] = 'Preserve nested loops/variables exactly as generated by EE CLI.';
            $commonMistakes[] = "Using single tag `{{$fieldName}}` for a complex field.";
            $commonMistakes[] = "Missing closing tag `{/{$fieldName}}`.";
        } else {
            $keyRules[] = "Single tag output is usually valid: `{{$fieldName}}`.";
        }

        return [
            'syntax_style' => $complex ? 'tag_pair_preferred' : 'single_tag_preferred',
            'key_rules' => $keyRules,
            'common_mistakes' => $commonMistakes,
        ];
    }

    /**
     * Apply conservative repairs to template snippet.
     *
     * @return array{
     *   fixed_snippet: string,
     *   applied_fixes: array<int, string>,
     *   used_scaffold: bool
     * }
     */
    public function fixSnippet(
        string $snippet,
        string $fieldName,
        bool $expectTagPair,
        string $scaffold,
        string $mode = 'safe'
    ): array {
        $fixed = $snippet;
        $applied = [];
        $usedScaffold = false;

        if ($mode === 'replace_with_scaffold') {
            return [
                'fixed_snippet' => $scaffold,
                'applied_fixes' => ['Replaced snippet with generated scaffold.'],
                'used_scaffold' => true,
            ];
        }

        if (trim($fixed) === '') {
            $fixed = $scaffold;
            $applied[] = 'Inserted generated scaffold into empty snippet.';
            $usedScaffold = true;

            return [
                'fixed_snippet' => $fixed,
                'applied_fixes' => $applied,
                'used_scaffold' => $usedScaffold,
            ];
        }

        $hasOpen = $this->hasOpeningTag($fixed, $fieldName);
        $hasClose = $this->hasClosingTag($fixed, $fieldName);
        $hasSingle = $this->hasSingleTag($fixed, $fieldName);

        if (! $hasOpen && ! $hasClose) {
            $fixed = $scaffold;
            $applied[] = "Snippet did not reference `{{$fieldName}}`; replaced with scaffold.";
            $usedScaffold = true;

            return [
                'fixed_snippet' => $fixed,
                'applied_fixes' => $applied,
                'used_scaffold' => $usedScaffold,
            ];
        }

        if ($expectTagPair && $hasSingle && ! $hasClose) {
            $fixed = $scaffold;
            $applied[] = 'Replaced single-tag usage with generated tag-pair scaffold for complex field.';
            $usedScaffold = true;

            return [
                'fixed_snippet' => $fixed,
                'applied_fixes' => $applied,
                'used_scaffold' => $usedScaffold,
            ];
        }

        if ($expectTagPair && $hasOpen && ! $hasClose) {
            $fixed = rtrim($fixed).PHP_EOL.'{/'.$fieldName.'}';
            $applied[] = "Added missing closing tag `{/{$fieldName}}`.";
        }

        if ($expectTagPair && ! $hasOpen && $hasClose) {
            $fixed = '{'.$fieldName.'}'.PHP_EOL.ltrim($fixed);
            $applied[] = "Added missing opening tag `{{$fieldName}}`.";
        }

        return [
            'fixed_snippet' => $fixed,
            'applied_fixes' => $applied,
            'used_scaffold' => $usedScaffold,
        ];
    }

    private function hasOpeningTag(string $snippet, string $fieldName): bool
    {
        $pattern = '/\{'.preg_quote($fieldName, '/').'(?:\s[^}]*)?\}/';

        return preg_match($pattern, $snippet) === 1;
    }

    private function hasClosingTag(string $snippet, string $fieldName): bool
    {
        $pattern = '/\{\/'.preg_quote($fieldName, '/').'\}/';

        return preg_match($pattern, $snippet) === 1;
    }

    private function hasSingleTag(string $snippet, string $fieldName): bool
    {
        $pattern = '/\{'.preg_quote($fieldName, '/').'\}/';

        return preg_match($pattern, $snippet) === 1;
    }
}
